//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArknightsResources.Operators.VoiceResources.JP.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArknightsResources.Operators.VoiceResources.JP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_12fce {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_12fce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_absin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_absin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_acast {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_acast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_acdrop {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_acdrop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_adnach {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_adnach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_aglina {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_aglina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_aguard {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_aguard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_akafyu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_akafyu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_amedic {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_amedic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_amgoat {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_amgoat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_amiya {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_amiya", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_amiya2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_amiya2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_angel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_angel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ansel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ansel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_aosta {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_aosta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_apionr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_apionr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_aprl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_aprl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_aprot2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_aprot2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_archet {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_archet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ardign {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ardign", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_asbest {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_asbest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ashlok {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ashlok", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_asnipe {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_asnipe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_astesi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_astesi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_aurora {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_aurora", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ayer {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ayer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_bdhkgt {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_bdhkgt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_beagle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_beagle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_beewax {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_beewax", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_bena {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_bena", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_bgsnow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_bgsnow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_bibeak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_bibeak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_billro {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_billro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_bison {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_bison", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_blackd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_blackd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_bldsk {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_bldsk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_blemsh {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_blemsh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_blkngt {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_blkngt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_bluep {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_bluep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_bpipe {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_bpipe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_breeze {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_breeze", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_broca {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_broca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_brownb {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_brownb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_bstalk {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_bstalk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_bubble {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_bubble", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_cammou {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_cammou", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_cast3 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_cast3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_catap {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_catap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ccheal {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ccheal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_cement {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_cement", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_cerber {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_cerber", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ceylon {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ceylon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_cgbird {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_cgbird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_chen {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_chen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_chen2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_chen2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_chiave {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_chiave", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_chimes {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_chimes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_chnut {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_chnut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_chyue {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_chyue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_clour {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_clour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_cqbw {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_cqbw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_cqbw_epoque {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_cqbw_epoque", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_crow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_crow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ctable {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ctable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_cutter {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_cutter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_cuttle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_cuttle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_dagda {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_dagda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_deepcl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_deepcl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_demkni {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_demkni", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_doberm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_doberm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_doroth {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_doroth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_durin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_durin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_durnar {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_durnar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_dusk {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_dusk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ebnhlz {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ebnhlz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_elysm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_elysm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_erato {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_erato", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_estell {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_estell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ethan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ethan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_excu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_excu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_excu2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_excu2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_f12yin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_f12yin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_falco {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_falco", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_fang {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_fang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_fartth {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_fartth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_finlpp {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_finlpp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_firwhl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_firwhl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_flameb {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_flameb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_flamtl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_flamtl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_flint {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_flint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_flower {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_flower", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_fmout {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_fmout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_folivo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_folivo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_folnic {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_folnic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_forcer {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_forcer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_franka {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_franka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_frncat {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_frncat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_frostl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_frostl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_frston {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_frston", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_gdglow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_gdglow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ghost {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ghost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ghost2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ghost2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_glacus {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_glacus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_glady {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_glady", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_glassb {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_glassb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_glaze {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_glaze", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_glider {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_glider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_gnosis {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_gnosis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_grani {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_grani", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_gravel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_gravel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_greyy {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_greyy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_greyy2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_greyy2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_gvial2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_gvial2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_gyuki {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_gyuki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_haak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_haak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_halo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_halo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_hamoni {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_hamoni", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_hbisc2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_hbisc2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_headbr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_headbr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_heidi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_heidi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_helage {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_helage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_heyak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_heyak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_hibisc {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_hibisc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_highmo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_highmo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_hmau {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_hmau", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_horn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_horn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_hpsts {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_hpsts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_hsguma {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_hsguma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_huang {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_huang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_humus {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_humus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ifrit {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ifrit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_indigo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_indigo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ines {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ines", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_inside {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_inside", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_irene {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_irene", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_iris {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_iris", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ironmn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ironmn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_jaksel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_jaksel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_jesica {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_jesica", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_jnight {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_jnight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_jpksel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_jpksel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_judge {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_judge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_kafka {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_kafka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_kalts {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_kalts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_kalts_boc {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_kalts_boc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_kazema {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_kazema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_kirara {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_kirara", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_kjera {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_kjera", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_kroos {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_kroos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_kroos2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_kroos2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_lava {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_lava", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_lava2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_lava2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_leizi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_leizi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_lin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_lin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ling {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_lionhd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_lionhd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_lisa {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_lisa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_liskam {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_liskam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_lmlee {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_lmlee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_lolxh {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_lolxh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_lolxh_1 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_lolxh_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_lumen {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_lumen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_lunacu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_lunacu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_malist {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_malist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mantic {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mantic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mberry {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_medic2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_medic2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_melan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_melan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_melnte {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_melnte", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_meteo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_meteo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mgllan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mgllan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_midn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_midn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_milu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_milu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mint {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mizuki {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mizuki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mlynar {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mlynar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mlyss {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mlyss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_moeshd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_moeshd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_morgan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_morgan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mostma {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mostma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mudrok {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mudrok", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_mudrok_1 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_mudrok_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_myrrh {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_myrrh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_myrtle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_myrtle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_nblade {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_nblade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_nearl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_nearl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_nearl2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_nearl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_nian {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_nian", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_nightm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_nightm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_nights {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_nights", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_noirc {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_noirc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_noirc2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_noirc2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_nothin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_nothin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_orchid {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_orchid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_otter {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_otter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_pallas {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_pallas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_panda {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_panda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_pasngr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_pasngr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_pasngr_epoque {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_pasngr_epoque", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_peacok {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_peacok", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_peper {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_peper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_phatom {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_phatom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_phenxi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_phenxi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_pianst {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_pianst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_pinecn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_pinecn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_platnm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_platnm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_plosis {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_plosis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_poca {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_poca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_podego {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_podego", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_popka {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_popka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_prove {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_prove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_provs {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_provs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_pudd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_pudd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_puzzle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_puzzle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_qanik {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_qanik", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_qiubai {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_qiubai", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_quartz {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_quartz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_quercu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_quercu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_rang {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_rang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_red {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_reed2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_reed2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_robin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_robin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_robrta {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_robrta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_rockr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_rockr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_rope {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_rope", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_rosmon {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_rosmon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_saga {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_saga", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_savage {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_savage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_scave {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_scave", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_sddrag {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_sddrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_serum {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_serum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_sesa {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_sesa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_shining {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_shining", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_shotst {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_shotst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_shwaz {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_shwaz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_sidero {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_sidero", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_siege {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_siege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_silent {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_silent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_skadi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_skadi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_skadi2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_skadi2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_skfire {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_skfire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_skgoat {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_skgoat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_slbell {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_slbell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_slchan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_slchan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_sleach {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_sleach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_slent2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_slent2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_snakek {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_snakek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_snsant {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_snsant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_sophia {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_sophia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_sora {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_sora", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_spikes {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_spikes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_spot {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_spot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_spuria {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_spuria", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_sqrrel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_sqrrel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_strong {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_strong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_stward {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_stward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_sunbr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_sunbr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_surtr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_surtr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_susuro {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_susuro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_svrash {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_svrash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_swire {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_swire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_swllow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_swllow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_takila {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_takila", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_texas {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_texas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_texas2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_texas2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_therex {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_therex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_thorns {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_thorns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_tiger {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_tiger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_tknogi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_tknogi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_toddi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_toddi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_tomimi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_tomimi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_totter {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_totter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_tuye {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_tuye", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_ulika {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_ulika", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_utage {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_utage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_vigil {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_vigil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_vigna {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_vigna", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_vodfox {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_vodfox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_waaifu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_waaifu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_weedy {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_weedy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_whispr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_whispr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_whitew {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_whitew", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_wildmn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_wildmn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_windft {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_windft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_wyvern {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_wyvern", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_yak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_yak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_yato2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_yato2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_yuki {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_yuki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_zebra {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_zebra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_jp_zumama {
            get {
                object obj = ResourceManager.GetObject("operator_voice_jp_zumama", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
