//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArknightsResources.Operators.VoiceResources.KR.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArknightsResources.Operators.VoiceResources.KR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_12fce {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_12fce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_adnach {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_adnach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_aglina {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_aglina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_amgoat {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_amgoat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_amiya {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_amiya", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_amiya2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_amiya2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_angel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_angel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_ansel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_ansel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_aprot2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_aprot2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_ardign {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_ardign", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_asbest {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_asbest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_ashlok {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_ashlok", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_aurora {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_aurora", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_beagle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_beagle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_bgsnow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_bgsnow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_bibeak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_bibeak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_blackd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_blackd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_bldsk {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_bldsk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_blkngt {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_blkngt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_bluep {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_bluep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_cast3 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_cast3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_ccheal {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_ccheal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_cgbird {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_cgbird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_chen {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_chen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_chen2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_chen2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_chnut {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_chnut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_cqbw {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_cqbw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_cqbw_epoque {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_cqbw_epoque", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_ctable {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_ctable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_deepcl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_deepcl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_demkni {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_demkni", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_doberm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_doberm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_doroth {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_doroth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_durin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_durin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_dusk {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_dusk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_ebnhlz {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_ebnhlz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_erato {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_erato", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_estell {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_estell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_excu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_excu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_falco {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_falco", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_fang {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_fang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_fartth {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_fartth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_flamtl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_flamtl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_flower {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_flower", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_fmout {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_fmout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_forcer {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_forcer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_franka {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_franka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_frncat {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_frncat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_frostl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_frostl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_gdglow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_gdglow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_ghost {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_ghost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_ghost2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_ghost2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_glassb {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_glassb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_glider {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_glider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_gnosis {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_gnosis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_grani {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_grani", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_gravel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_gravel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_greyy {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_greyy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_greyy2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_greyy2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_gvial2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_gvial2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_gyuki {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_gyuki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_halo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_halo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_hbisc2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_hbisc2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_headbr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_headbr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_heidi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_heidi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_hibisc {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_hibisc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_horn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_horn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_hpsts {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_hpsts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_hsguma {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_hsguma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_ifrit {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_ifrit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_irene {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_irene", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_jesica {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_jesica", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_jnight {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_jnight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_kazema {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_kazema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_kjera {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_kjera", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_kroos {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_kroos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_kroos2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_kroos2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_lava {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_lava", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_lava2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_lava2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_ling {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_ling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_liskam {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_liskam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_lmlee {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_lmlee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_lumen {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_lumen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_malist {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_malist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_mantic {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_mantic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_mberry {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_mberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_medic2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_medic2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_melan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_melan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_meteo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_meteo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_mgllan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_mgllan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_milu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_milu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_mlynar {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_mlynar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_moeshd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_moeshd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_myrrh {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_myrrh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_myrtle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_myrtle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_nblade {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_nblade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_nearl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_nearl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_nearl2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_nearl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_nian {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_nian", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_nights {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_nights", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_noirc {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_noirc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_orchid {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_orchid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_otter {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_otter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_panda {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_panda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_peacok {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_peacok", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_phatom {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_phatom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_phenxi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_phenxi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_pianst {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_pianst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_platnm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_platnm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_plosis {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_plosis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_poca {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_poca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_popka {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_popka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_prove {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_prove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_provs {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_provs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_pudd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_pudd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_quercu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_quercu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_rang {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_rang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_red {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_robrta {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_robrta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_rockr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_rockr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_rope {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_rope", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_savage {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_savage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_scave {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_scave", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_serum {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_serum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_shining {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_shining", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_shotst {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_shotst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_shwaz {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_shwaz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_sidero {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_sidero", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_siege {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_siege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_skadi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_skadi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_skadi2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_skadi2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_skfire {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_skfire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_skgoat {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_skgoat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_slbell {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_slbell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_slchan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_slchan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_sleach {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_sleach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_snakek {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_snakek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_sora {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_sora", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_spot {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_spot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_sqrrel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_sqrrel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_stward {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_stward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_sunbr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_sunbr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_surtr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_surtr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_svrash {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_svrash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_swire {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_swire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_texas {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_texas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_tiger {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_tiger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_utage {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_utage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_vigna {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_vigna", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_whitew {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_whitew", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_wildmn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_wildmn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_windft {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_windft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_wyvern {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_wyvern", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_yak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_yak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_kr_yuki {
            get {
                object obj = ResourceManager.GetObject("operator_voice_kr_yuki", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
