//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArknightsResources.Operators.VoiceResources.EN.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArknightsResources.Operators.VoiceResources.EN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_12fce {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_12fce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_acast {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_acast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_adnach {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_adnach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_aglina {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_aglina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_aguard {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_aguard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_amedic {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_amedic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_amgoat {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_amgoat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_amiya {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_amiya", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_amiya2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_amiya2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_angel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_angel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ansel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ansel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_aprot2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_aprot2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ardign {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ardign", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ash {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ashlok {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ashlok", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_asnipe {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_asnipe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_aurora {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_aurora", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_beagle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_beagle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_bgsnow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_bgsnow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_blackd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_blackd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_bldsk {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_bldsk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_blitz {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_blitz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_blkngt {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_blkngt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_bluep {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_bluep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ccheal {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ccheal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_cgbird {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_cgbird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_chen {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_chen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_chen2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_chen2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ctable {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ctable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_dagda {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_dagda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_demkni {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_demkni", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_doberm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_doberm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_durin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_durin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_dusk {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_dusk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ebnhlz {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ebnhlz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_estell {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_estell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_falco {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_falco", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_fang {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_fang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_fartth {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_fartth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_fmout {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_fmout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_forcer {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_forcer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_frostl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_frostl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_gdglow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_gdglow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ghost {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ghost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ghost2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ghost2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_glassb {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_glassb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_glider {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_glider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_gnosis {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_gnosis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_gravel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_gravel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_gvial2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_gvial2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_halo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_halo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_hbisc2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_hbisc2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_heidi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_heidi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_hibisc {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_hibisc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_horn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_horn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_hsguma {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_hsguma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ines {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ines", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_irene {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_irene", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ironmn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ironmn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_jesica {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_jesica", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_jnight {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_jnight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_kazema {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_kazema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_kjera {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_kjera", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_kroos {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_kroos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_kroos2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_kroos2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_lava {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_lava", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_lava2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_lava2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_ling {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_ling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_liskam {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_liskam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_lmlee {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_lmlee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_lumen {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_lumen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_malist {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_malist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_mberry {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_mberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_melan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_melan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_meteo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_meteo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_myrrh {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_myrrh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_myrtle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_myrtle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_nblade {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_nblade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_nearl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_nearl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_nearl2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_nearl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_nian {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_nian", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_noirc {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_noirc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_orchid {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_orchid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_panda {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_panda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_peper {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_peper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_phatom {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_phatom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_phenxi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_phenxi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_pianst {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_pianst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_platnm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_platnm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_plosis {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_plosis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_pudd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_pudd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_quercu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_quercu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_rang {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_rang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_rfrost {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_rfrost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_robrta {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_robrta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_rockr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_rockr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_rope {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_rope", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_scave {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_scave", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_serum {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_serum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_shining {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_shining", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_shotst {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_shotst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_siege {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_siege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_slbell {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_slbell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_slchan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_slchan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_sleach {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_sleach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_sqrrel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_sqrrel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_stward {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_stward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_svrash {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_svrash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_swire {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_swire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_tachak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_tachak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_texas {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_texas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_tiger {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_tiger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_totter {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_totter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_wildmn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_wildmn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_yak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_yak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_en_yuki {
            get {
                object obj = ResourceManager.GetObject("operator_voice_en_yuki", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
