//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArknightsResources.Operators.VoiceResources.CN.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArknightsResources.Operators.VoiceResources.CN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_12fce {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_12fce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_absin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_absin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_acast {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_acast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_acdrop {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_acdrop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_adnach {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_adnach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_aglina {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_aglina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_aguard {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_aguard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_amedic {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_amedic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_amgoat {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_amgoat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_amiya {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_amiya", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_amiya2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_amiya2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_angel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_angel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ansel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ansel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_aosta {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_aosta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_apionr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_apionr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_aprl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_aprl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_aprot2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_aprot2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_archet {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_archet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ardign {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ardign", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_asbest {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_asbest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ashlok {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ashlok", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_asnipe {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_asnipe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_astesi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_astesi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_aurora {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_aurora", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ayer {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ayer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_bdhkgt {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_bdhkgt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_beagle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_beagle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_beewax {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_beewax", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_bgsnow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_bgsnow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_bibeak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_bibeak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_bison {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_bison", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_blackd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_blackd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_bldsk {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_bldsk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_blemsh {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_blemsh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_blkngt {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_blkngt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_bluep {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_bluep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_bpipe {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_bpipe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_breeze {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_breeze", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_broca {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_broca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_brownb {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_brownb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_bstalk {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_bstalk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_bubble {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_bubble", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_cammou {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_cammou", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_cast3 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_cast3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_catap {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_catap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ccheal {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ccheal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_cerber {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_cerber", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ceylon {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ceylon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_cgbird {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_cgbird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_chen {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_chen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_chen2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_chen2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_chiave {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_chiave", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_chimes {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_chimes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_chnut {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_chnut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_chyue {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_chyue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_clour {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_clour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_cqbw {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_cqbw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_cqbw_epoque {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_cqbw_epoque", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ctable {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ctable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_cutter {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_cutter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_cuttle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_cuttle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_dagda {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_dagda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_deepcl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_deepcl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_demkni {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_demkni", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_doberm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_doberm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_doroth {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_doroth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_durin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_durin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_durnar {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_durnar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_dusk {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_dusk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ebnhlz {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ebnhlz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_elysm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_elysm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_erato {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_erato", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_estell {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_estell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ethan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ethan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_excu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_excu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_f12yin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_f12yin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_falco {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_falco", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_fang {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_fang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_fartth {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_fartth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_finlpp {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_finlpp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_firwhl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_firwhl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_flameb {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_flameb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_flamtl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_flamtl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_flint {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_flint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_flower {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_flower", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_fmout {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_fmout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_folivo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_folivo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_folnic {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_folnic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_forcer {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_forcer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_franka {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_franka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_frncat {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_frncat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_frostl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_frostl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_gdglow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_gdglow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ghost {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ghost", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ghost2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ghost2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_glacus {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_glacus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_glassb {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_glassb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_glaze {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_glaze", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_glider {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_glider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_gnosis {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_gnosis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_grani {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_grani", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_gravel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_gravel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_greyy {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_greyy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_greyy2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_greyy2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_gvial2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_gvial2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_gyuki {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_gyuki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_haak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_haak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_halo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_halo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_hamoni {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_hamoni", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_hbisc2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_hbisc2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_headbr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_headbr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_heidi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_heidi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_helage {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_helage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_hibisc {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_hibisc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_highmo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_highmo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_hmau {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_hmau", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_horn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_horn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_hpsts {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_hpsts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_hsguma {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_hsguma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_huang {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_huang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ifrit {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ifrit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_irene {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_irene", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_iris {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_iris", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ironmn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ironmn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_jaksel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_jaksel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_jesica {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_jesica", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_jnight {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_jnight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_judge {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_judge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_kafka {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_kafka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_kazema {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_kazema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_kjera {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_kjera", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_kroos {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_kroos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_kroos2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_kroos2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_lava {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_lava", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_lava2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_lava2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_leizi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_leizi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_lin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_lin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ling {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_lisa {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_lisa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_liskam {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_liskam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_lmlee {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_lmlee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_lolxh {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_lolxh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_lolxh_1 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_lolxh_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_lumen {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_lumen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_lunacu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_lunacu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_malist {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_malist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_mantic {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_mantic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_mberry {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_mberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_medic2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_medic2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_melan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_melan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_meteo {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_meteo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_mgllan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_mgllan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_midn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_midn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_milu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_milu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_mint {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_mint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_mlynar {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_mlynar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_mm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_mm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_moeshd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_moeshd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_mostma {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_mostma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_mudrok {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_mudrok", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_mudrok_1 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_mudrok_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_myrrh {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_myrrh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_myrtle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_myrtle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_nblade {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_nblade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_ncdeer {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_ncdeer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_nearl {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_nearl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_nearl2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_nearl2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_nian {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_nian", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_nightm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_nightm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_nights {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_nights", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_noirc {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_noirc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_nothin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_nothin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_orchid {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_orchid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_otter {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_otter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_panda {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_panda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_pasngr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_pasngr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_pasngr_epoque {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_pasngr_epoque", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_peacok {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_peacok", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_peper {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_peper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_phatom {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_phatom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_phenxi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_phenxi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_pianst {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_pianst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_pinecn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_pinecn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_platnm {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_platnm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_plosis {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_plosis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_poca {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_poca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_podego {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_podego", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_popka {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_popka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_prove {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_prove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_provs {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_provs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_pudd {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_pudd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_puzzle {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_puzzle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_qanik {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_qanik", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_qiubai {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_qiubai", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_quartz {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_quartz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_quercu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_quercu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_rang {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_rang", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_red {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_reed2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_reed2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_robin {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_robin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_robrta {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_robrta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_rockr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_rockr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_rope {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_rope", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_rosmon {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_rosmon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_saga {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_saga", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_savage {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_savage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_scave {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_scave", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_sddrag {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_sddrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_serum {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_serum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_sesa {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_sesa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_shining {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_shining", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_shotst {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_shotst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_shwaz {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_shwaz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_sidero {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_sidero", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_siege {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_siege", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_silent {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_silent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_skadi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_skadi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_skadi2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_skadi2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_skfire {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_skfire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_skgoat {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_skgoat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_slbell {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_slbell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_slchan {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_slchan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_sleach {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_sleach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_snakek {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_snakek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_snsant {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_snsant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_sophia {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_sophia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_sora {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_sora", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_spikes {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_spikes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_spot {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_spot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_sqrrel {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_sqrrel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_strong {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_strong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_stward {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_stward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_sunbr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_sunbr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_surtr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_surtr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_susuro {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_susuro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_svrash {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_svrash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_swire {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_swire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_swllow {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_swllow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_texas {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_texas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_texas2 {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_texas2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_therex {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_therex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_thorns {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_thorns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_tiger {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_tiger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_tknogi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_tknogi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_tomimi {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_tomimi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_totter {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_totter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_tuye {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_tuye", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_utage {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_utage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_vigil {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_vigil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_vigna {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_vigna", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_vodfox {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_vodfox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_waaifu {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_waaifu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_weedy {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_weedy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_whispr {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_whispr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_whitew {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_whitew", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_wildmn {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_wildmn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_windft {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_windft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_wyvern {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_wyvern", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_yak {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_yak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_yuki {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_yuki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_zebra {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_zebra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_voice_cn_zumama {
            get {
                object obj = ResourceManager.GetObject("operator_voice_cn_zumama", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
